sudo: required

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install verilator
  - sudo apt-get install libboost-all-dev

language: cpp

script:
  - git submodule init
  - git submodule update
  - mkdir build
  - pushd build
  - cmake ../
  - make
